INSERT INTO glams (glam_type, name, date_established, location,  description, url)
VALUES ("Museums", "Jorge B. Vargas Museum and Filipiniana Research Center", 1978, "Roxas Avenue, UP Campus, Diliman, Quezon City 1101", "The Jorge B. Vargas Museum and Filipiniana Research Center is one of the nine museums and galleries in the University of the Philippines (UP) Diliman campus. A center for Philippine art and culture, its main thrusts are research, curation, and education.", "https://vargasmuseum.org/wp-content/uploads/2021/08/DSC03316.jpg");
INSERT INTO glams (glam_type, name, date_established, location,  description, url)
VALUES ("Galleries", "Parola UP Fine Arts Gallery", 1987, "Bartlett Hall, E. Jacinto St., UP Diliman, Quezon City 1101", "The UP Fine Arts Gallery, is an integral part of the College of Fine Arts, hosting exhibits, events, talks and performances since it was housed in the Corredor and Foyer galleries at UPD Bartlett Hall.", "https://i0.wp.com/cfa.upd.edu.ph/wp-content/uploads/2022/10/IMG_3326.jpg?fit=1536%2C1152&ssl=1");
INSERT INTO glams (glam_type, name, date_established, location,  description, url)
VALUES ("Libraries", "College of Science LIbrary", 1975, "College of Science Library, Velasquez St., National Science Complex, UP Campus, Diliman, Quezon City 1101", "The UP Diliman Science Library is a center of excellence for science information in support of teaching, extension and research activities of the UP College of Science.", "https://cslib.science.upd.edu.ph/wp-content/uploads/2021/02/10492239_423577014481564_2176252219709868230_n.jpg");
INSERT INTO glams (glam_type, name, date_established, location,  description, url)
VALUES ("Libraries", "College of Arts and Letters Library", 1985, "Ground Floor, CAL New Bldg., Roxas Ave., UP Campus, Diliman, Quezon City", "The School of Economics Library has an extensive collection of books, monographs, periodicals, and other documents. With holdings of more than 90,000 volumes, the collection is one of the finest economics collections in English in Southeast Asia, with a unique strength in Philippine economic literature.", "https://library.econ.upd.edu.ph/wp-content/uploads/2021/05/20210223_153622-scaled.jpg");
INSERT INTO glams (glam_type, name, date_established, location,  description, url)
VALUES ("Archives", "The University Archives Division", 1975, "Main Library at Apacible St., Diliman Quezon City", "The UP Archives is the official repository for valuable records and papers of the University of the Philippines (UP). It includes Board of Regents' records, publications, reports, memorabilia, and more. It showcases UP's contributions to the 1989 Centennial of the Republic of the Philippines.", "https://i0.wp.com/up.edu.ph/wp-content/uploads/2017/10/Archives.jpg?resize=768%2C512&ssl=1")